[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["sagudev <samo.golez@outlook.com>"]
edition = "2018"
default-run = "day1"

[lib]
name = "aoc"
path = "src/lib.rs"

[[bin]]
name = "dayx"
path = "src/bin/dayx.rs"

[[bin]]
name = "day1"
path = "src/bin/day1.rs"

[dependencies]
